name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: JUnit Report Action
        # You may pin to the exact commit or the version.
        # uses: mikepenz/action-junit-report@41a3188dde10229782fd78cd72fc574884dd7686
        uses: mikepenz/action-junit-report@v3.0.3
        with:
          # Specify the token to use to publish the check.
          token: "${{ secrets.GITHUB_TOKEN }}" # optional, default is ${{ github.token }}
          # Deprecated syntax to specify github token.
          github_token:
          # Xml report paths in glob format
          report_paths: # optional, default is **/junit-reports/TEST-*.xml
          # Comma seperated list of source folders to ignore for lookup
          exclude_sources: # optional, default is /build/,/__pycache__/
          # Regular expression for the named test suites
          suite_regex: # optional, default is
          # Enable to only annotate the results on the files, will not create a check run.
          annotate_only: # optional, default is false
          # Defines if the active check should be updated instead
          update_check: # optional, default is false
          # Check name for test reports.
          check_name: # optional, default is JUnit Test Report
          # Commit SHA to update the check status.
          commit: # optional
          # Fail the build in case a test failure occurred.
          fail_on_failure: # optional, default is false
          # Fail if no test are found.
          require_tests: # optional, default is false
          # Include passed tests in the report
          include_passed: # optional, default is false
          # Template to configure the title format. Placeholders: {{FILE_NAME}}, {{SUITE_NAME}}, {{TEST_NAME}}.
          check_title_template: # optional
          # Additional text to summary output
          summary: # optional, default is
          # If a testcase is retried, ignore the original failure.
          check_retries: # optional, default is false

      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: desktop:dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            desktop/build/libs/*.jar
